name: "Build and push docker"
description: "Build and push docker image"

inputs:
  DOCKERHUB:
    describtion: "Enable/Disable dockerhub login"
    default: 'true'
  DOCKERHUB_USERNAME:
    description: "Dockerhub username used to read public images"
    required: true
  DOCKERHUB_TOKEN:
    description: "Dockerhub token used to read public images"
    required: true

  GHCR:
    description: "Login to ghcr.io"
    default: 'true'
  GITHUB_TOKEN:
    description: "Token from secrets.GITHUB_TOKEN"
    required: true

  AWS:
    description: "If we should use AWS"
    default: 'true'
  AWS_ACCESS_KEY_ID:
    description: "AWS access key used to write to ECR"
    required: false
  AWS_SECRET_ACCESS_KEY:
    description: "AWS secret access key used to write to ECR"
    required: false
  AWS_REGION:
    description: "AWS region"
    required: false
  AWS_ROLE:
    description: "AWS role to use"
    required: false

outputs:
  ecr_registry:
    description: "ECR registry"
    value: ${{ steps.ecr.outputs.registry }}

runs:
  using: "composite"
  steps:
    - name: Apply nf_conntrack_tcp_be_liberal kernel change
      shell: bash
      run: |
        sudo sh -c "echo 1 > /proc/sys/net/netfilter/nf_conntrack_tcp_be_liberal"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      if: ${{ inputs.DOCKERHUB == 'true' }}
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.DOCKERHUB_USERNAME }}
        password: ${{ inputs.DOCKERHUB_TOKEN }}

    - name: Configure AWS credentials
      if: ${{ inputs.AWS == 'true' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.AWS_REGION }}
        role-to-assume: ${{ inputs.AWS_ROLE }}
        mask-aws-account-id: false
        role-duration-seconds: 1200

    - name: Login to Amazon ECR
      if: ${{ inputs.AWS == 'true' }}
      id: ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'true'

    - name: Login to GitHub Container Registry
      if: ${{ inputs.GHCR == 'true' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.GITHUB_TOKEN }}
