name: "Build and push docker"
description: "Build and push docker image"

inputs:
  DOCKERHUB_USERNAME:
    description: "Dockerhub username used to read public images"
    required: true
  DOCKERHUB_TOKEN:
    description: "Dockerhub token used to read public images"
    required: true

  GITHUB_TOKEN:
    description: "Token from secrets.GITHUB_TOKEN"
    required: true

  AWS:
    description: "If we should use AWS"
    default: true

  AWS_ACCESS_KEY_ID:
    description: "AWS access key used to write to ECR"
    required: false
  AWS_SECRET_ACCESS_KEY:
    description: "AWS secret access key used to write to ECR"
    required: false
  AWS_REGION:
    description: "AWS region"
    required: false
  AWS_ROLE:
    description: "AWS config to use"
    required: false

outputs:
  ecr_registry:
    description: "ECR registry"
    value: ${{ steps.ecr.outputs.registry }}

runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      if: ${{ !github.event.pull_request.head.repo.fork }}
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.DOCKERHUB_USERNAME }}
        password: ${{ inputs.DOCKERHUB_TOKEN }}

    - name: Configure AWS credentials
      if: ${{ !github.event.pull_request.head.repo.fork && inputs.AWS == 'true' }}
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ inputs.AWS_ROLE }}
        mask-aws-account-id: false
        role-duration-seconds: 1200

    - name: Set up buildkitd
      shell: bash
      run: |
        docker run -d \
          --privileged \
          --name remote-buildkit \
          -p 1234:1234 \
          -v "${HOME}/.aws/config:/root/.aws/config:ro" \
          -v "${HOME}/.aws/credentials:/root/.aws/credentials:ro" \
          moby/buildkit:v0.11.5 \
          --addr unix:///run/buildkit/buildkitd.sock \
          --addr tcp://0.0.0.0:1234

    - name: Cache buildx
      id: cache-buildx
      uses: actions/cache@v3
      with:
        path: ~/.docker/cli-plugins/docker-buildx
        key: ${{ runner.os }}-cache-buildx

    - name: Build buildx
      if: steps.cache-buildx.outputs.cache-hit != 'true'
      shell: bash
      run: |
        docker buildx bake "https://github.com/docker/buildx.git"
        mkdir -p ~/.docker/cli-plugins
        mv ./bin/build/buildx ~/.docker/cli-plugins/docker-buildx

    - name: Buildx version
      shell: bash
      run: |
        docker buildx version

    - name: Buildx create
      shell: bash
      id: buildx-create
      run: |
        docker buildx create --driver remote docker-container://remote-buildkit --use

    - name: Login to Amazon ECR
      if: ${{ !github.event.pull_request.head.repo.fork && inputs.AWS == 'true' }}
      id: ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Login to GitHub Container Registry
      if: ${{ !github.event.pull_request.head.repo.fork }}
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.GITHUB_TOKEN }}
