name: "Integration Verify"
description: "Verify using Maven"

#inputs:

runs:
  using: "composite"
  steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github

      - name: Date cache
        shell: bash
        run: date +%F > /tmp/owasp-cve-cache-date

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
          restore-keys: v1-dependencies-

      - name: Owasp cache
        uses: actions/cache@v3
        id: owasp-cache
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: owasp-cve-cache-{{ checksum "/tmp/owasp-cve-cache-date" }}
          restore-keys: owasp-cve-cache-

      - if: steps.owasp-cache.outputs.cache-hit != 'true'
        name: Owasp update
        shell: bash
        run: mvn -s $GITHUB_WORKSPACE/.github/settings.xml -e org.owasp:dependency-check-maven:update-only

      - if: steps.owasp-cache.outputs.cache-hit != 'true'
        name: Cache owasp update
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: owasp-cve-cache-{{ checksum "/tmp/owasp-cve-cache-date" }}
          restore-keys: owasp-cve-cache-

      - name: Maven verify
        shell: bash
        run: mvn -s $GITHUB_WORKSPACE/.github/settings.xml -e verify -DskipTests

      - name: Upload dependency check reports
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html

