name: "Run yarn"
description: "Run yarn commands with version and cache"

inputs:
  node_version:
    description: "node version"
  install_command:
    description: "Install command"
    default: "yarn install --frozen-lockfile"
  command:
    description: "Command to execute"
    default: ""
  lock_file:
    description: "Path to lockfile"
    default: "yarn.lock"
  path:
    description: "Path to project"
    default: "."
  cache_key:
    description: "Specify cache key"
    default: "dependencies"
  use_cache:
    description: "Set to 'false' to disable cache"
    default: "true"
  FONTAWESOME_TOKEN:
    description: "Fontawesome Token"
  VERDACCIO_TOKEN:
    description: "Verdaccio Token"
  GITHUB_TOKEN:
    description: "Github token"

runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.use_cache == 'true'
      id: dependencies
      uses: actions/cache@v4
      with:
        path: ${{ inputs.path }}/node_modules
        key: ${{ inputs.cache_key }}-${{ hashFiles(inputs.lock_file) }}
        restore-keys:
          dependencies-

    - name: Add .yarnrc.yml or .npmrc
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        rm -f .npmrc
        if yarn --version | grep -q '^1\.'; then
          echo "Detected yarn v1 => adding .npmrc"
          if test -n "${{ inputs.FONTAWESOME_TOKEN }}"; then
            cat << EOF >> .npmrc
        @fortawesome:registry=https://npm.fontawesome.com/
        //npm.fontawesome.com/:_authToken="${{ inputs.FONTAWESOME_TOKEN }}"
        EOF
          fi
          if test -n "${{ inputs.VERDACCIO_TOKEN }}"; then
            cat << EOF >> .npmrc
        @voltti:registry=https://npm.sst.espoon-voltti.fi/
        //npm.sst.espoon-voltti.fi/:_authToken="${{ inputs.VERDACCIO_TOKEN }}"
        //npm.sst.espoon-voltti.fi/:always-auth=true
        EOF
          fi
          if test -n "${{ inputs.GITHUB_TOKEN }}"; then
            cat << EOF >> .npmrc
        @espoon-voltti:registry=https://npm.pkg.github.com
        //npm.pkg.github.com/:always-auth=true
        //npm.pkg.github.com/:_authToken=${{ inputs.GITHUB_TOKEN }}
        EOF
          fi
        else
          echo "Detected yarn v2 or later => adding .yarnrc.yml"
          if test -n "${{ inputs.FONTAWESOME_TOKEN }}"; then
            yarn config set npmScopes.fortawesome.npmRegistryServer "https://npm.fontawesome.com"
            yarn config set npmScopes.fortawesome.npmAlwaysAuth true
            yarn config set 'npmRegistries["https://npm.fontawesome.com"].npmAuthToken' "${{ inputs.FONTAWESOME_TOKEN }}"
          fi
          if test -n "${{ inputs.VERDACCIO_TOKEN }}"; then
            yarn config set npmScopes.voltti.npmRegistryServer "https://npm.sst.espoon-voltti.fi"
            yarn config set npmScopes.voltti.npmAlwaysAuth true
            yarn config set 'npmRegistries["https://npm.sst.espoon-voltti.fi"].npmAuthToken' "${{ inputs.VERDACCIO_TOKEN }}"
          fi
          if test -n "${{ inputs.GITHUB_TOKEN }}"; then
            yarn config set npmScopes.espoon-voltti.npmRegistryServer "https://npm.pkg.github.com"
            yarn config set npmScopes.espoon-voltti.npmAlwaysAuth true
            yarn config set 'npmRegistries["https://npm.pkg.github.com"].npmAuthToken' "${{ inputs.GITHUB_TOKEN }}"
          fi
        fi

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}

    - if: ${{ inputs.install_command && steps.dependencies.outputs.cache-hit != 'true' }}
      working-directory: ${{ inputs.path }}
      shell: bash
      run: ${{ inputs.install_command }}

    - if: ${{ inputs.command }}
      working-directory: ${{ inputs.path }}
      shell: bash
      run: ${{ inputs.command }}
